### PR TITLE
fix the npm install from github recursive install cause by the node_modules symbol link

### PR DESCRIPTION
**Pull request by kopinions**
When the node_modules(example/{get,headers,post,streaming}/node_modules/http-browserify) is symbol link, when install from github(npm install tradle/http-browserify), the npm will recursively install the node_modules. npm can not install the dependence from github.

### CODE REVIEW

**Comment by mvayngrib** [comment]
great catch with the symbolic link! 

I think you can just remove the whole `example` folder instead, as all the examples are for the browser rather than react-native.

**Comment by kopinions** [comment]
so just remove the example ?

**Comment by mvayngrib** [comment]
@sjkyspa yea, they don't work anyway, they're just leftovers from the http-browserify fork

**Comment by kopinions** [comment]
@mvayngrib example removed, please merge it.

**Comment by mvayngrib** [comment]
@sjkyspa can you revert the name change in package.json and the example section in readme?

**Comment by kopinions** [comment]
@mvayngrib name change in package.json is used when install from the github.  example section in readme is removed.

**Comment by mvayngrib** [comment]
@sjkyspa changing the name in package.json will make this module impossible to install from npm, as there is another module called `react-native-http`. If you want to install this module from github, just run `npm i -S tradle/react-native-http`, then in code: `require('@tradle/react-native-http')`

**Comment by kopinions** [comment]
@mvayngrib  I have give up this. Just use my own.

**Comment by jupmorenor** [comment]
Does this package let me create a http server in my phone??

**Comment by mvayngrib** [comment]
@jupmorenor no, only make http requests

**Pull request closed without merging**
